apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # 추후 AWS ECR 주소로 변경
        image: wysiwyg-backend:latest 
        ports:
        - containerPort: 8080